// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace LivrariaControleEmprestimo.DATA.Models
{
    public partial class Cliente
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Required]
        [Column("CPF")]
        [StringLength(14)]
        public string Cpf { get; set; }
        [Required]
        [Column("nome")]
        [StringLength(100)]
        public string Nome { get; set; }
        [Required]
        [Column("endereco")]
        [StringLength(50)]
        public string Endereco { get; set; }
        [Required]
        [Column("cidade")]
        [StringLength(50)]
        public string Cidade { get; set; }
        [Required]
        [Column("bairro")]
        [StringLength(50)]
        public string Bairro { get; set; }

        [InverseProperty("IdNavigation")]
        public virtual LivroClienteEmprestimo LivroClienteEmprestimo { get; set; }
    }
}