// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace LivrariaControleEmprestimo.DATA.Models
{
    public partial class ControleEmprestimoLivroContext : DbContext
    {
        public ControleEmprestimoLivroContext()
        {
        }

        public ControleEmprestimoLivroContext(DbContextOptions<ControleEmprestimoLivroContext> options)
            : base(options)
        {
        }

        public virtual DbSet<TbCliente> TbCliente { get; set; }
        public virtual DbSet<TbLivro> TbLivro { get; set; }
        public virtual DbSet<TbLivroClienteEmprestimo> TbLivroClienteEmprestimo { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. See http://go.microsoft.com/fwlink/?LinkId=723263 for guidance on storing connection strings.
                optionsBuilder.UseSqlServer("Data Source=LAPTOP-N3KBHKL3;Initial Catalog=ControleEmprestimoLivro;Integrated Security=True");
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<TbCliente>(entity =>
            {
                entity.Property(e => e.Id).ValueGeneratedNever();

                entity.Property(e => e.CliBairro).IsUnicode(false);

                entity.Property(e => e.CliCidade).IsUnicode(false);

                entity.Property(e => e.CliCpf).IsUnicode(false);

                entity.Property(e => e.CliEndereco).IsUnicode(false);

                entity.Property(e => e.CliNome).IsUnicode(false);

                entity.Property(e => e.CliNumero).IsUnicode(false);

                entity.Property(e => e.CliTelefoneCelular).IsUnicode(false);

                entity.Property(e => e.CliTelefoneFixo).IsUnicode(false);
            });

            modelBuilder.Entity<TbLivro>(entity =>
            {
                entity.Property(e => e.Id).ValueGeneratedNever();

                entity.Property(e => e.LivroAutor).IsUnicode(false);

                entity.Property(e => e.LivroEdicao).IsUnicode(false);

                entity.Property(e => e.LivroEditora).IsUnicode(false);

                entity.Property(e => e.LivroNome).IsUnicode(false);
            });

            modelBuilder.Entity<TbLivroClienteEmprestimo>(entity =>
            {
                entity.Property(e => e.Id).ValueGeneratedNever();

                entity.HasOne(d => d.LceIdClienteNavigation)
                    .WithMany(p => p.TbLivroClienteEmprestimo)
                    .HasForeignKey(d => d.LceIdCliente)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Livro_Cliente_Emprestimo_Cliente");

                entity.HasOne(d => d.LceIdLivroNavigation)
                    .WithMany(p => p.TbLivroClienteEmprestimo)
                    .HasForeignKey(d => d.LceIdLivro)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Livro_Cliente_Emprestimo_Livro");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}